### ISSUE TITLE
Why does the run_app_mac.sh have git clone as well?

### ISSUE THREAD

**Issue by nutmilk10** [ajayarunachalam/pychatgpt_gui#1]
Not sure why the bash script needs to git glone again after you do that during the intial setup? Aren't you just creating a very nested project? And there is a typo, gui is missing the g in the shell script

**Comment by ajayarunachalam** [comment]
Hi, Thanks for informing the typo, will correct that. Yes, the bash script is run as a standalone setup assuming the user won't go through the initial steps one-by-one and just run the bash to configure everything
